### PR TITLE
add 'withConnect'

### PR DESCRIPTION
**Pull request by ocramz**

### CODE REVIEW

**Comment by chrisdone** [comment]
Cool - can you put it in `MonadUnliftIO`?

**Comment by ocramz** [comment]
Will do soon @chrisdone , I'm just a bit caught up with work these days. However, I'd also like to use `odbc` _at_ work soon.

**Comment by ocramz** [comment]
@chrisdone in the latest commit `withConnection` returns in MonadUnliftIO :)

**Comment by chrisdone** [comment]
Thanks!

**Pull request merged**
